### ISSUE TITLE
argon2: can't find `SaltString::generate` from the example in the doc

### ISSUE THREAD

**Issue by Geobert** [RustCrypto/password-hashes#125]
Hi,

I'm trying to use `argon2` and following the example I'm encountering an issue with `SaltString::generate` which can't be found.

What am I missing here?

Thanks!

**Comment by tarcieri** [comment]
Apologies, this was something of a gap in v0.1.0 API (which you can probably guess from the version number is an initial release).

I've released v0.1.1 (#127) which adds an enabled-by-default `rand` feature which should make it available.

Can you confirm it addresses your issue?

**Comment by Geobert** [comment]
Yes it did! Thank you!
