### ISSUE TITLE
scrypt: password-hash is a bit annoying

### ISSUE THREAD

**Issue by lnicola** [RustCrypto/password-hashes#138]
The example in https://docs.rs/scrypt/0.6.2/scrypt/ doesn't work because the `password_hash` dependency is missing the `rand_core` feature. Users need to add `password-hash` as a dependency and enable that feature.

It's enabled in the `dev-dependencies`, which is why `cargo` doesn't complain.

**Comment by tarcieri** [comment]
Sorry, there was a similar issue in `pbkdf2` (#130). Let me get that taken care of.
