### ISSUE TITLE
Accelerate scrypt using SIMD

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/password-hashes#16]
`scrypt` spends most of the time in `salsa20_8` function, which can be significantly accelerated using explicit SIMD.

**Comment by tarcieri** [comment]
Per #29, an interesting way to do this would be to add SIMD support to the `salsa20` crate, then use its implementation of Salsa20/8

**Comment by tarcieri** [comment]
As of #60, which switches to using the `salsa20` crate, we can now track SIMD optimizations here: https://github.com/RustCrypto/stream-ciphers/issues/50
