### ISSUE TITLE
[Question] Raw output of the Argon2 hash?

### ISSUE THREAD

**Issue by sciguyryan** [RustCrypto/password-hashes#206]
Hi there.

I have looked through the docs and I can't seem to find what I am looking for. Is it possible to get the raw output when using the Argon2 hash, when using the default parameters?

I'm specifically looking for any method to get the raw bytes of the hash, using _hashed_password_simple_ doesn't give the output I am looking. I need to get the raw bytes as these will be used as an AES key. The output of the  _hashed_password_simple_ function is a string and contains superfluous data (for my intended use case).

If you could point me in the right direction that would be greatly appreciated!

Thanks in advance.

**Comment by tarcieri** [comment]
The low-level API is [`hash_password_into`](https://docs.rs/argon2/0.2.4/argon2/struct.Argon2.html#method.hash_password_into)

**Comment by sciguyryan** [comment]
Thanks, that seems to be exactly what I needed!
