### ISSUE TITLE
Argon2 uses wrong value for thread count

### ISSUE THREAD

**Issue by gansn** [RustCrypto/password-hashes#234]
Seems like a copy paste error introduced in #213. Error is in line 102:
https://github.com/RustCrypto/password-hashes/blob/a09fa2316769d7444d30a0be0dbd9ee281f8fcd6/argon2/src/instance.rs#L96-L104

Surely the number of threads has nothing to do with `t_cost`, the number of passes?

It used to use the value of `context.threads`, which is just `parallelism` (aka `lanes`):
https://github.com/RustCrypto/password-hashes/blob/3bfc4d9a5fa281916f39cfc700736115af3ac950/argon2/src/instance.rs#L98-L106

@tarcieri

**Comment by tarcieri** [comment]
PR to fix this: #235 

It's a bit disturbing this wasn't caught by any of the current test vectors
