### ISSUE TITLE
bcrypt_pbkdf: Support passphase that's &[u8] and not &str

### ISSUE THREAD

**Issue by alex** [RustCrypto/password-hashes#276]
The only thing that's done with the passphrase is pass `Sha512::digest(passphrase.as_bytes())` so it should be fine to allow it to be arbitrary bytes.

This probably needs to be done by either a) making passphrase's type generic, b) adding a second function

**Comment by tarcieri** [comment]
Elsewhere we use `impl AsRef<[u8]>` which is polymorphic over `&[u8]` and `&str` (among other types)
