### ISSUE TITLE
sha512crypt index out of bounds

### ISSUE THREAD

**Issue by masmullin2000** [RustCrypto/password-hashes#327]
The function produce_byte_seq() will cause an index out of bounds panic if the password supplied to sha512_crypt has a length larger than 64 bytes.

**Comment by kevoh1516** [comment]
I'm having the same issues when using pbkdf2 with sha256 and sha512.

**Comment by tarcieri** [comment]
@kevoh1516 can you file a separate issue with a reproduction of your problem?

**Comment by kevoh1516** [comment]
Sure.

**Comment by tarcieri** [comment]
@masmullin2000 you didn't provide a reproduction for this issue.

There are test vectors for passwords which are 65, 127, 128, and 129-bytes long.

Closing this as lacking a reproduction and covered by the existing test vectors.

**Comment by tarcieri** [comment]
Fixed in #328
