### ISSUE TITLE
add a convenient way for common pbkdf2::<Hmac<Sha1>>(*** )

### ISSUE THREAD

**Issue by sxci** [RustCrypto/password-hashes#335]
eg:
```
let mut bytes = [0u8; 16];
pbkdf2::<Hmac<Sha1>>(password, b"saltysalt", 1003, bytes.as_mut());
```
go lang : https://pkg.go.dev/golang.org/x/crypto/pbkdf2
```
dk := pbkdf2.Key([]byte(password), []byte("saltysalt"), 1003, 16, sha1.New)
```
in rust, there are  additional info:  mut bytes , Hmac,
golang's pbkdf2.Key look like more convenient

**Comment by newpavlov** [comment]
It comes to different philosophies between Rust and Go. Go is quite happy to use dynamic dispatch and heap allocated data, while in Rust we prefer monomorphization and stack-based structures. Note that PBKDF2 is defined in terms of a keyed PRF, HMAC is just one example of such function. For example, BLAKE2 functions can be used as such function directly without HMAC.

**Comment by tarcieri** [comment]
@newpavlov perhaps an allocating API like `pbkdf2_vec` which accepts an output length argument ala Go would be a useful addition?
