### ISSUE TITLE
Support PHC String Format

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/password-hashes#34]
[Modular Crypt Format](https://passlib.readthedocs.io/en/stable/modular_crypt_format.html) has been deprecated in favor of [PHC String Format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md). Since MCF is still widely used we probably should support both. I think ideally it should be done as part of new traits for password hashing algorithms.

**Comment by tarcieri** [comment]
I implemented the PHC string format in a prospective `password-hash` crate in this PR: https://github.com/RustCrypto/traits/pull/437

**Comment by tarcieri** [comment]
As of the latest releases, `argon2` and `pbkdf2` both support the PHC string format.

The main remaining crate it'd be good to add support to is `scrypt`.

I'm not aware if there are well-specified parameters for the other crates (`sha-crypt` might be good to investigate)

**Comment by tarcieri** [comment]
https://github.com/RustCrypto/password-hashes/pull/111 implements the PHC string format for scrypt.

I'll call this issue done for now, but feel to comment / reopen if there are additional applicable password hashes.

**Comment by tarcieri** [comment]
Took a look at SHA-crypt. It uses the same Base64 alphabet as bcrypt:

https://text.nxg.me.uk/2019/1

...so unfortunately that isn't compatible with a PHC hash.
