### ISSUE TITLE
Scrypt bug on android platform

### ISSUE THREAD

**Issue by tmpfs** [RustCrypto/password-hashes#340]
I have run into a bug with `scrypt` on android where key derivation appears to be indeterministic but I have no idea where the actual error is. I wonder if you have any ideas...

The code works as expected on MacOS.

Here is the sample I am testing derived from the code in `eth-keystore-rs`:

```rust
fn test_scrypt() -> Result<()> {
    use scrypt::{scrypt, Params as ScryptParams};
    use rand::RngCore;

    let password = b"foo";

    const DEFAULT_KEY_SIZE: usize = 32usize;
    const DEFAULT_KDF_PARAMS_DKLEN: u8 = 32u8;
    const DEFAULT_KDF_PARAMS_LOG_N: u8 = 13u8;
    const DEFAULT_KDF_PARAMS_R: u32 = 8u32;
    const DEFAULT_KDF_PARAMS_P: u32 = 1u32;

    let mut rng = rand::thread_rng();

    // Generate a random salt.
    let mut salt = vec![0u8; DEFAULT_KEY_SIZE];
    rng.fill_bytes(salt.as_mut_slice());

    // Derive the key.
    let mut key1 = vec![0u8; DEFAULT_KDF_PARAMS_DKLEN as usize];
    let scrypt_params = ScryptParams::new(
        DEFAULT_KDF_PARAMS_LOG_N,
        DEFAULT_KDF_PARAMS_R,
        DEFAULT_KDF_PARAMS_P,
    )?;
    scrypt(password.as_ref(), &salt, &scrypt_params, key1.as_mut_slice())?;

    let mut key2 = vec![0u8; DEFAULT_KDF_PARAMS_DKLEN as usize];
    let n = 2u32.pow(DEFAULT_KDF_PARAMS_LOG_N as u32);
    let p =  DEFAULT_KDF_PARAMS_P;
    let r =  DEFAULT_KDF_PARAMS_R;

    let log_n = (n as f32).log2() as u8;
    let scrypt_params = ScryptParams::new(log_n, r, p)?;

    scrypt(password.as_ref(), &salt, &scrypt_params, key2.as_mut_slice())?;

    assert_eq!(key1, key2);

    log::info!("key derivation ok");

    Ok(())
}
```

It is quite tedious to test as we need to build the shared library using `cargo ndk` and then link it into an Android program and run on an emulator/device.

Any ideas how we can go about debugging this problem?

**Comment by newpavlov** [comment]
Can you change `thread_rng` to a PRNG seeded with a fixed seed (you could use the `rand_chacha` crate) and run the test in loop to find a salt value which triggers the issue and check whether the failure happens always with the same salt?

**Comment by tarcieri** [comment]
> I have run into a bug with scrypt on android where key derivation appears to be indeterministic

Can you describe the problem in more detail? As @newpavlov mentioned, your test is using an RNG, so the output is nondeterministic by definition.

Specifically I'm curious what is "working" on macOS but not on Android. Can you give an example of an assertion which is succeeding on one platform but failing on the other?

**Comment by tarcieri** [comment]
It would be good to add an assertion like this (e.g. above the other `assert_eq!), just to make sure your `log_n` computation is successfully round tripping the original value:

```rust
assert_eq!(DEFAULT_KDF_PARAMS_LOG_N, log_n);
```

**Comment by tmpfs** [comment]
Thanks @tarcieri and @newpavlov.

It was a floating point rounding issue on Android (`12 != 13`).

Using `ceil()` as a workaround for now:

```rust
    // TODO: use int_log https://github.com/rust-lang/rust/issues/70887
    // TODO: when it is stable
    let log_n = (n as f32).log2().ceil() as u8;
```

Will submit a PR to `eth-keystore-rs`.

Appreciate the help and your libraries, thank you 🙏
