### ISSUE TITLE
implement password_hash's traits for sha_crypt

### ISSUE THREAD

**Issue by ibotty** [RustCrypto/password-hashes#346]
Is there any reason (except that they should not to be used for new code) not to implement the password_hash's traits?

Maybe marked with `deprecated` attribute to not be used.

**Comment by tarcieri** [comment]
@ibotty the `password-hash` crate implements the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md), which is different from the freeform Modular Crypt Format (MCF) typically used with SHA-crypt.

To make it work with the `password-hash` crate, we'd need a specification for how to encode SHA-crypt using the PHC format.

I'm personally not aware of such a specification. It wouldn't be too difficult to adapt the MCF parameters to the PHC format, but if there is an existing PHC encoding we can use as a reference, we should target that for interop purposes.
