### ISSUE TITLE
Argon2: ergonomics as KDF

### ISSUE THREAD

**Issue by rubdos** [RustCrypto/password-hashes#353]
The API of the Argon2 implementation seems to be very much tailored for the password *verification* case (verifying the hash), not necessarily so for the password-based KDF case (where the hash is used as symmetric key).

In the verification case, the whole `PasswordHash` object can be serialized and stored, and later verified with the `PasswordVerifier`. In the KDF case, I need to manually dissect the `PasswordHash` into the parameters and the hash itself. I manually store the parameters (with `ParamsString`), and in the authentication phase, I need this kind of boilerplate to reassemble the `Params`:

```rust
        let params_string = argon2::password_hash::ParamsString::from_str(&auth.params)?;
        let mut params = ParamsBuilder::new();
        params
            .m_cost(params_string.get_decimal("m").unwrap())?
            .t_cost(params_string.get_decimal("t").unwrap())?
            .p_cost(params_string.get_decimal("p").unwrap())?;
        let argon2 = Argon2::new(
            argon2::Algorithm::Argon2id,
            argon2::Version::try_from(auth.version)?,
            params
                .params()?,
        );
        let PasswordHash {
            algorithm: _,
            version: _,
            params: _,
            salt: _,
            hash,
        } = argon2
            .hash_password(password.as_ref(), &auth.salt)?;
```

I think this kind of construction could reside in big part in the `argon2` implementation (some common implementation that parses a `ParamsString` into a `Params`). Manually doing could be error-prone (I'm sure someone of RustCrypto will point me at a mistake), and takes quite some time to understand the API and tailor it to the KDF case.

I'm also wondering about the `ParamsString` → `Params` convertion in terms of parsing untrusted data, but that's probably a topic for another time.

**Comment by tarcieri** [comment]
For the KDF use case, you should be using [`Argon2::hash_password_into`](https://docs.rs/argon2/latest/argon2/struct.Argon2.html#method.hash_password_into).

**Comment by rubdos** [comment]
> For the KDF use case, you should be using [`Argon2::hash_password_into`](https://docs.rs/argon2/latest/argon2/struct.Argon2.html#method.hash_password_into).

Aha, that makes sense. Then again, the `Params` situation is still quite annoying; is there something to be done about that?

**Comment by tarcieri** [comment]
Not really. It sounds like you want to handle the parameters like they're a password hash, while actually using Argon2 as a KDF, which isn't exactly a common way to use it.

Most schemes which specify use a password-based KDF also provide their own way to encode the parameters.

**Comment by rubdos** [comment]
> Most schemes which specify use a password-based KDF also provide their own way to encode the parameters.

Sounded fair enough, and it's indeed a lot simpler using your own parameter encoding and using `Argon2::hash_password_into`. Thanks!
