### ISSUE TITLE
blake2 dep has been yanked

### ISSUE THREAD

**Issue by cemoktra** [RustCrypto/password-hashes#354]
the blake2  version argon2 requires has been yanked

**Comment by newpavlov** [comment]
Perform `cargo update` and it should get `blake2 v0.10.5`.

**Comment by cemoktra** [comment]
Not really as the dependency is specifically saying `blake2 = { version = "0.10.4", default-features = false }`

**Comment by newpavlov** [comment]
Read https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

`version = "0.10.4"` is equivalent to `version = "^0.10.4"`, meaning `0.10.5` is compatible with it.

**Comment by cemoktra** [comment]
but `cargo deny` complains

**Comment by cemoktra** [comment]
which i could fix. sorry
