### ISSUE TITLE
Ability to zeroize Output

### ISSUE THREAD

**Issue by mikedilger** [RustCrypto/password-hashes#362]
pbkdf2 is recommended for stretching passwords into encryption keys.  Under such usage, the output of the hashing function is sensitive key material and needs to be zeroize-able. But currently it's opaque and I don't see any mutable functionality on it.

**Comment by tarcieri** [comment]
In KDF applications you should use the low-level interface:

https://docs.rs/pbkdf2/latest/pbkdf2/fn.pbkdf2.html

It writes its output to a mutable byte slice

**Comment by mikedilger** [comment]
Thanks.
