### ISSUE TITLE
Update argon2 default Params to match OWASP Cheat Sheet

### ISSUE THREAD

**Issue by bracketttc** [RustCrypto/password-hashes#369]
The [OWASP Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html) (also linked in the `README.md`!) recommends argon2id Params as follows:
> - m=37MB, t=1, p=1
> - m=15MB, t=2, p=1

The current defaults in the argon2 crate are m=4MB, t=3, p=1 if I'm reading the documentation correctly.

I think this would constitute a breaking change for existing users who use the defaults.

**Comment by tarcieri** [comment]
We're in the middle of a breaking release cycle, so making these sorts of changes is fine. Note that for PHC string outputs at least, the parameters used are encoded in the resulting hash string, which eases the burden of these sorts of incremental updates.

We also have #331 open to evaluate a different set of defaults.

**Comment by bracketttc** [comment]
OWASP updated their work factor recommendations today.

**Comment by bracketttc** [comment]
Sorry, overly enthusiastic and on my phone. Recommendation for PBKDF2-SHA256 went up to 600,000 and I made the assumption that other methods would have similar changes.

**Comment by tarcieri** [comment]
Updated in #386.

I also did scrypt in #388 and PBKDF2 in #389
