### ISSUE TITLE
Rustify the argon2 API

### ISSUE THREAD

**Issue by dns2utf8** [RustCrypto/password-hashes#371]
Hi all

I am implementing my master thesis and had some trouble using the argon2 crate.
After reading through the source code I think I understand what is going on with the `Salt` and `SaltString` 

I prepared a branch for merging, but I seem to be unable to open a pull request:
https://github.com/dns2utf8/password-hashes/tree/rustify_the_api

What do you think?
Best, Stefan

**Comment by tarcieri** [comment]
If you'd like to propose some API changes, please open a PR

**Comment by dns2utf8** [comment]
I am trying, currently having an issue opening it :sweat_smile: 
![grafik](https://user-images.githubusercontent.com/739070/214431956-687d73a1-fccc-468c-bdf1-ad2b11951d31.png)

**Comment by dns2utf8** [comment]
Solved the issue :+1:
