### ISSUE TITLE
argon2: SaltInvalid(TooLong) for existing password hashes

### ISSUE THREAD

**Issue by weiznich** [RustCrypto/password-hashes#403]
This is more a feature/support request than a bug report. I'm well aware [of the documentation](https://docs.rs/password-hash/0.5.0/password_hash/struct.Salt.html#constraints) that states that the size of a salt should be between 16 and 64 byte.

Now I'm trying to migrate an existing codebase from the rather old [argon2rs](https://crates.io/crates/argon2rs) to `argon2`. In that codebase we need to support existing password hashes stored in a database. These hashes use for some reason salts larger than 64 bytes. Is there anything that could be done about that? Would you be willing to accept a PR to change the `Salt` type to optionally allow larger hashes, by for example using a `tinyvec::TinyVec` as inner buffer?

**Comment by tarcieri** [comment]
Are these salts PHC strings starting with `$argon2...`, or inputs to e.g. `Argon2::hash_password_into`? The latter should already accept large salt values.

As for PHC strings, the maximum length is part of the PHC string specification:

https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md

> The salt value is encoded in B64. The length in bytes of the salt is between 8 and 48 bytes(*), thus yielding a length in characters between 11 and 64 characters (and that length is never equal to 1 modulo 4). 

Accepting longer salt values would mean we're out-of-spec, which would create interoperability problems with implementations which do follow the spec (which is possibly what you're experiencing now).

If argon2rs was allowing longer salt values in PHC strings, that's a bug in argon2rs.

**Comment by weiznich** [comment]
Thanks for your response. Yes the values stored in the database are PHC strings. They start with `$argon2…`. The pointer to `Argon2::hash_password_into` is really helpful. With that + some manual parsing I'm able to verify the old passwords correctly. For reference see the following example:

```rust
    let plain_password = "super secret";
    let hash = b"uioduearuvlaaeaveaelvueiaeuvleelveuaeuvleiauevlueiucle";
//    let hash = b"abcluveouvloiaelv";
    let parameters = argon2rs::Argon2::default(argon2rs::Variant::Argon2i);
    let password_hash =
        argon2rs::verifier::Encoded::new(parameters, plain_password.as_bytes(), hash, &[], &[])
            .to_u8();

    let s = std::str::from_utf8(&password_hash).unwrap();

    let hashed_pwd = argon2::PasswordHash::new(&s[..std::cmp::min(s.len(), 88)]).unwrap();
    let algorithm = argon2::Algorithm::new(hashed_pwd.algorithm.as_str()).unwrap();
    let version = match hashed_pwd.version {
        None => argon2::Version::V0x10,
        Some(16) => argon2::Version::V0x10,
        Some(19) => argon2::Version::V0x13,
        _ => unreachable!(),
    };
    let params = argon2::Params::new(
        hashed_pwd.params.get_decimal("m").unwrap(),
        hashed_pwd.params.get_decimal("t").unwrap(),
        hashed_pwd.params.get_decimal("p").unwrap(),
        None,
    )
    .unwrap();

    let p = s.split('$').collect::<Vec<_>>();
    let pwd = argon2::password_hash::Output::b64_decode(p[p.len() - 1]).unwrap();
    let pwd = pwd.as_bytes();
    let salt = argon2::password_hash::Output::b64_decode(p[p.len() - 2]).unwrap();
    let salt = salt.as_bytes();

    let a = argon2::Argon2::new(algorithm, version, params);

    let mut b = vec![0; pwd.len()];

    a.hash_password_into(plain_password.as_bytes(), &salt, &mut b)
        .unwrap();
    assert_eq!(pwd, b);
```

(For simplicity that just constructs a password hash via `argon2rs`.)

A proper implementation should likely check the password with the `argon2` provided mechanism first and only if that fail fall back to the method demonstrated above.

Hopefully that's useful for others as well.

I consider that issue as being resolved.
