### ISSUE TITLE
different results on .NET Rfc2898DeriveBytes

### ISSUE THREAD

**Issue by lca85** [RustCrypto/password-hashes#406]
Why rust and .NET results are different?
rust code from doc
```
use hex_literal::hex;
use pbkdf2::{pbkdf2_hmac, pbkdf2_hmac_array};
use sha2::Sha256;

let password = b"password";
let salt = b"salt";
// number of iterations
let n = 4096;
// Expected value of generated key
let expected = hex!("c5e478d59288c841aa530db6845c4c8d962893a0");

let mut key1 = [0u8; 20];
pbkdf2_hmac::<Sha256>(password, salt, n, &mut key1);
```
key1 output: c5e478d59288c841aa530db6845c4c8d962893a0
.net result 
```
public static void  Test_Rfc2898DeriveBytes()
{
    var rgb = new Rfc2898DeriveBytes("password", Encoding.Unicode.GetBytes("salt"), 4096,HashAlgorithmName.SHA256);
    var rgbKey = rgb.GetBytes(20);
    Console.WriteLine(Convert.ToHexString(rgbKey));
}
```
output: 15D8244DC001D18AA2538EED52B83C304E039963
So why i am getting c5e478d59288c841aa530db6845c4c8d962893a0 form rust and in .net 15D8244DC001D18AA2538EED52B83C304E039963

**Comment by tarcieri** [comment]
From the documentation for `Rfc2898DeriveBytes`:

https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=net-7.0

> Implements password-based key derivation functionality, PBKDF2, by using a pseudo-random number generator based on [HMACSHA1](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha1?view=net-7.0).

Your Rust example is using SHA-256. The .NET version is using SHA-1.

**Comment by tarcieri** [comment]
Oh, I guess, that was obscured in the code example above until I scrolled.

Offhand I'm not sure why the results are different then.

Your Rust example also doesn't show how you're printing `key1`.

**Comment by newpavlov** [comment]
Can you check what you get for [RFC 6070](https://www.rfc-editor.org/rfc/rfc6070) vectors? If you get the same values, then it's likely that `Rfc2898DeriveBytes` has remnants of SHA-1 which are not influenced by the last argument.

**Comment by lca85** [comment]
Thanks guys for your help.
I am closing this.
I found that the issue is on my c# code, specifically on the salt array initialization.
so this c# code now outputs the same result as in the pbkdf2 crate doc page https://docs.rs/pbkdf2/latest/pbkdf2/#examples

```
public static void  Test_Rfc2898DeriveBytes()
{
    byte[] salt = new byte[4] { 115,97,108,116};//salt
    var rgb = new Rfc2898DeriveBytes("password", salt, 4096,HashAlgorithmName.SHA256);
    var rgbKey = rgb.GetBytes(20);
    Console.WriteLine(Convert.ToHexString(rgbKey).ToLower());
}
```
Thanks again :)
