### ISSUE TITLE
Output max length : 86 instead of 64

### ISSUE THREAD

**Issue by oganexon** [RustCrypto/password-hashes#413]
Hi, 

Quoting from the documentation,

> # Constraints
> The above guidelines are interpreted into the following constraints:
> 
> - Minimum length: **10**-bytes (80-bits)
> - Maximum length: **64**-bytes (512-bits)
> 
> The specific recommendation of a 64-byte maximum length is taken as a best
> practice from the hash output guidelines for [Argon2 Encoding][2] given in
> the same document:
> 
> > The hash output...length shall be between 12 and 64 bytes (16 and 86
> > characters, respectively). The default output length is 32 bytes
> > (43 characters).
> Based on this guidance, this type enforces an upper bound of 64-bytes
> as a reasonable maximum, and recommends using 32-bytes.

64 seems to be a reasonable maximum, but 86 is sometimes needed for legacy purposes.

I'm currently working with sha512 hashes, and the hash output is 86 characters long. This hard limit is an absolute blocker for me, as I can't do anything to work my way around.

86 characters max is clearly stated as possible per the Argon2 specs, why not using this value ?

Respectfully

**Comment by tarcieri** [comment]
`Output::MAX_LENGTH` reflects the maximum length of the *raw binary output* of the password hash.

For SHA-512, that's 64-bytes, so you should be just fine.

It's possible there's a bug where something is misinterpreting that as the length prior to decoding. If you think a bug like that exists, can you post a reproduction?

**Comment by oganexon** [comment]
Thanks for the clarification, indeed 86 characters in base64 represent 64 bytes.

My problem was that I had to encode in base64, then decode to make it work.
```rust
Output::new(base64ct::Base64Bcrypt::decode(&encode_sha512(&hash), &mut buf).unwrap())
```
