### ISSUE TITLE
Is `Argon2::default()` forward compatible?

### ISSUE THREAD

**Issue by TheCGDF** [RustCrypto/password-hashes#424]
Currently, `Argoin2::default` is using `Argon2id v19`,  if I use `default(Argon2id v19)` to hash password now, will it still can be verified by `Argon2id v20 or higher` in the future?

**Comment by tarcieri** [comment]
It works when computing password hash strings, which include all relevant algorithm parameters. In fact, that's how the [`password-auth`](https://github.com/RustCrypto/password-hashes/tree/master/password-auth) crate works.

If you're using Argon2 as a KDF you are responsible for either hardcoding or encoding the parameters yourself.
