### ISSUE TITLE
password-auth: provide an API to expose whether a password should be re-hashed

### ISSUE THREAD

**Issue by belak** [RustCrypto/password-hashes#426]
Ideally there would be a way to "upgrade" passwords from a deprecated method to a supported one, similar to passlib's [verify_and_update](https://passlib.readthedocs.io/en/stable/lib/passlib.context.html#passlib.context.CryptContext.verify_and_update) method.

This would allow users of this crate verify a password, check if it's using the most up-to-date hashing method, and return the updated hash so it can be stored elsewhere.

**Comment by tarcieri** [comment]
I agree that some API to detect password hashes using obsolete algorithms would be good. However, one of the goals of `password-auth` is to provide a simple, unobtrusive API, so unlike passlib I don't want to add a ton of API surface such that it obscures the simple happy path of `generate_hash`/`verify_password`.

I'm also not sold on the `verify_and_update` API (or name). I think we can break password hash updates down to two different approaches:

- *lazy interactive updates*: the `verify_and_update` approach where updating a password hash requires the user's original password, and passwords are replaced as users login. This approach assumes old password hashes are weak enough they deserve updating, but not so weak that they need to be updated immediately and the old hashing algorithms disabled (a sort of uncanny valley in the threat model)
- *eager non-interactive updates*: updates which can be bulk-applied across the entire password database without requiring users to login. There are many approaches to this, but the most common is a "[password onion](https://bristolcrypto.blogspot.com/2015/01/password-hashing-according-to-facebook.html)" approach which looks something like `H2(H1(password, salt), ...)`. Some password hashing schemes also support offline work-factor updates or even more [advanced schemes](https://rwc.iacr.org/2016/Slides/Pass-RWC.pdf) (e.g based on bilinear pairings).

In my experience as a security professional the latter approach is far and away the one preferred by users at scale. The first may feel like good security hygiene but as I noted with the "uncanny valley" remark is hard to fit into a threat model, and has a major disadvantage that hash upgrades don't immediately help all users, only the ones who have recently logged in.

We can avoid painting ourselves into a corner and mandating one of these approaches while also keeping the API surface smaller by introducing a function which checks if the algorithm/params used by a particular password hash is considered suboptimal. Such a function avoids the question of "do I need the user's original password to upgrade the hash?" and allows for either lazy or eager updates to password hashes.

Passlib calls such a function [`needs_update`](https://passlib.readthedocs.io/en/stable/lib/passlib.context.html#passlib.context.CryptContext.needs_update), although I don't think that's a particularly good name and would prefer something a bit less ambiguous as a free function imported to a module dealing with a number of different concerns (e.g. related to user authentication).

How about something like this instead?

```rust
fn is_hash_obsolete(hash: &str) -> bool
```

I think that strikes a nice balance between simplicity and flexibility.

**Comment by belak** [comment]
Thanks for the quick and thoughtful response!

I was under the impression that what you described as `lazy interactive updates` are more common, but I'm also not a security expert. I was familiar with it from passlib and the [django.contrib.auth](https://github.com/django/django/blob/main/django/contrib/auth/hashers.py#L67-L78) packages.

If I understand correctly, most of the things mentioned in `eager non-interactive updates` would require additional work in password-auth to support. The password onion and other bulk application approaches are new to me, but they seem very interesting. Maybe that would be worth a separate issue? Though it would take a bit of API design work to get it right and support it in the other hashing-related crates.

I think your proposal of `is_hash_obsolete` strikes a nice balance between convenience and flexibility. It would allow for building a system that does automatic hash upgrades, or requiring people to change their password if the hash was obsolete. The downside to that approach as-described is that it wouldn't support a password onion or other eager updates, though as mentioned above I assume you'd need to build additional APIs to support that anyway.

**Comment by tarcieri** [comment]
Opened #428

**Comment by belak** [comment]
Wow, that was fast. Thanks for doing this!
