### ISSUE TITLE
argon2: const ParamsBuilder 

### ISSUE THREAD

**Issue by C0D3-M4513R** [RustCrypto/password-hashes#436]
Can the ParamsBuilder methods be made const?
Const fn's would help out, because then I could make the Params object a Compile time const.
I took a little look at the code and saw no obvious reason why it should not be possible.

```rust
const PARAMS:argon2::Params = match argon2::ParamsBuilder::new().build() {
    Ok(v) => v,
    Err(_) => panic!("Failed to create argon2 params"),
};
```

https://github.com/RustCrypto/password-hashes/blob/master/argon2/src/params.rs#L367

**Comment by tarcieri** [comment]
It seems like `new` and `build` are the only methods of `ParamsBuilder` that could be made `const fn` as the setters require `&mut self`. That seems like a circuitous way of returning the default `Params`.

If that's all you want, we could hoist out the `Default` impl into a proper constant: https://github.com/RustCrypto/password-hashes/blob/c29e6d7/argon2/src/params.rs#L189-L196

**Comment by tarcieri** [comment]
The PR auto-closed it as completed when it was merged, then the tests failed on `master`
