### ISSUE TITLE
PBKDF2 defult number of rounds not correct?

### ISSUE THREAD

**Issue by olback** [RustCrypto/password-hashes#441]
The following is a snippet from [`simple.rs`](https://github.com/RustCrypto/password-hashes/blob/pbkdf2-v0.12.1/pbkdf2/src/simple.rs#L177-L195):

```rs
impl Params {
    /// Recommended number of PBKDF2 rounds (used by default).
    ///
    /// This number is adopted from the [OWASP cheat sheet]:
    ///
    /// > Use PBKDF2 with a work factor of 600,000 or more
    ///
    /// [OWASP cheat sheet]: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
    pub const RECOMMENDED_ROUNDS: usize = 600_000;
}

impl Default for Params {
    fn default() -> Params {
        Params {
            rounds: 10_000,
            output_length: 32,
        }
    }
}
```
Is the Default impl correct here? Shouldn't it be something like this instead?
```rs
impl Default for Params {
    fn default() -> Params {
        Params {
            rounds: Self::RECOMMENDED_ROUNDS,
            output_length: 32,
        }
    }
}
```

I'd be happy to send a PR if this is the case.

Side note: The [security advisory](https://github.com/RustCrypto/password-hashes/security/advisories/new) link in `SECURITY.md` does not work.

**Comment by tarcieri** [comment]
Yes, please prepare a PR.

Also the security advisory reporting should be enabled now.

**Comment by olback** [comment]
Aight, see #442
