### ISSUE TITLE
argon2: make it works well with `thiserror`.

### ISSUE THREAD

**Issue by Hapenia-Lans** [RustCrypto/password-hashes#446]
<img width="321" alt="image" src="https://github.com/RustCrypto/password-hashes/assets/93276898/5e627e35-ea90-4641-b146-79613781af44">

<img width="657" alt="image" src="https://github.com/RustCrypto/password-hashes/assets/93276898/6ddb9eec-b584-4d8e-9063-2ce067f00b8b">

it should be a simple fix.

**Comment by newpavlov** [comment]
You need to enable the `std` feature. In v0.6 it may be worth to make it enabled by default.

**Comment by Hapenia-Lans** [comment]
Thanks! It works, I will close this.
