### ISSUE TITLE
argon2 does not zeroize derived key

### ISSUE THREAD

**Issue by sekinfo** [RustCrypto/password-hashes#485]
I have made a simple app to test zeroizing with the argon2 crate, and scanmem finds several instances of the derived key on the stack after `hash_password_into_with_memory` and all user-defined buffers are zeroed.

Code and full details are given here: https://git.sr.ht/~sekinfo/test_argon2_with_zeroize

Am I using the zeroize feature correctly?

**Comment by tarcieri** [comment]
Stack spilling is a common problem in Rust code and there's little we can do regarding transient secrets left on the stack after an operation is complete.

Unless you see an obvious culprit in our code, that is the most common cause of these sorts of issues.

**Comment by sekinfo** [comment]
Thank you for your reply!

As I understand it, one must allocate secrets on the heap (using Box for example) and be very careful to avoid transient copies in order to have successful zeroization.

There exists the [secrecy crate](https://docs.rs/secrecy/latest/secrecy/) which uses this approach.

Is there another way currently to use the zeroize feature of the argon2 crate such that it works as expected?

**Comment by tarcieri** [comment]
To really solve the problem properly we'd likely need support from the compiler, as suggested here: https://github.com/rust-lang/rfcs/issues/1853

See also: https://eprint.iacr.org/2023/1713

**Comment by newpavlov** [comment]
>As I understand it, one must allocate secrets on the heap (using Box for example) and be very careful to avoid transient copies in order to have successful zeroization.

Not quite, during algorithm execution compiled code may place temporary variables on stack, which later may be observed by an assembly-level attacker or by inspecting memory dump, this behavior is commonly called "stack spilling". And it's not practical to fight this using `zeroize` and `Drop` impls, especially in Rust with its move semantics.

The only practical option is to "bleach stack" after you finished to work with sensitive data, i.e. overwrite memory bellow stack pointer (stack usually grows down) with zeros. Unfortunately, we currently do not have ways to estimate upper bound for compiled algorithm's stack usage during compile time (often compiler has the necessary information, but it's too low in the pipeline), so we either have to guess or measure this size directly, but the size may change in a different compiler version or after a small code change, so this approach is not completely reliable. Alternatively, we could erase the whole stack (e,g, on Linux we can get information about thread's stack), but it's often very inefficient, especially if you do not change the default stack size.

**Comment by newpavlov** [comment]
Closing this issue since we can not do much about it with the current state of Rust.
