### ISSUE TITLE
Scrypt default parameters

### ISSUE THREAD

**Issue by cbzehner** [RustCrypto/password-hashes#49]
So after looking at a few different argon2 implementations I decided to use scrypt because it's already maintained by this organization.

It looks relatively straightforward to use:
```rust
// First setup the ScryptParams arguments with:
// r = 8, p = 1, n = 32768 (log2(n) = 15)
let params = ScryptParams::new(15, 8, 1).unwrap();
// Hash the password for storage
let hashed_password = scrypt_simple("Not so secure password", &params)
    .expect("OS RNG should not fail");
// Verifying a stored password
assert!(scrypt_check("Not so secure password", &hashed_password).is_ok());
```

But the very first section threw me off, as an experienced web developer without a crypto background.
```rust
// --snip
// First setup the ScryptParams arguments with:
// r = 8, p = 1, n = 32768 (log2(n) = 15)
let params = ScryptParams::new(15, 8, 1).unwrap();
// --snip
```
I stopped and asked myself, what is `ScryptParams` and why does it take these arbitrary values? Do I need to replace these values with ones of my own for security? How do I know what values are reasonable? 😱

I found a [lovely blog post](https://blog.filippo.io/the-scrypt-parameters/) explaining that these are the defaults from the original paper (it also suggests they might need to be revisited?). So for now I'm just going to copy the example from the docs verbatim.

However, I'd like to propose that we could make this API friendlier if we omitted the `&params` and set it as a default the same way the [`salt` is handled currently](https://docs.rs/scrypt/0.4.0/src/scrypt/simple.rs.html#41).

**Comment by cbzehner** [comment]
That makes sense. Once RustCrypto/traits#263 is complete, would it make sense to remove the `::new` API? I don't fully understand why a default would be provided for the salt but not the scrypt params?

**Comment by newpavlov** [comment]
>would it make sense to remove the ::new API?

I don't think so. Sometimes you do need control over algorithm parameters, e.g. if you want higher security level or if you have to be compatible with existing software.

BTW `ScryptParams` has the [`recommended`](https://docs.rs/scrypt/0.4.0/scrypt/struct.ScryptParams.html#method.recommended) method which you can use for now.

**Comment by cbzehner** [comment]
Thanks. The `recommended` method is exactly what I was looking for.

Would you be interested in a PR changing the [documentation example](https://github.com/RustCrypto/password-hashes/blob/master/scrypt/src/lib.rs#L20-L22) for `scrypt_simple` to use `ScryptParams::recommended()` instead of manually configuring the params?

If not, please close out this issue. Thanks for answering my questions!

**Comment by newpavlov** [comment]
>Would you be interested in a PR changing the documentation example for scrypt_simple to use ScryptParams::recommended() instead of manually configuring the params?

Yes, it makes sense. Can you submit a PR with those changes?
