### ISSUE TITLE
are these 2 different parameters basically the same?

### ISSUE THREAD

**Issue by fu3x11** [RustCrypto/password-hashes#493]
argon2id
iterations: 20
mem cost: 250 mb

argon2id
iterations: 2
mem cost: 5gb

does this basically have more memory over time? will these be equally just as hard to crack in all circumstances

**Comment by tarcieri** [comment]
One is using more memory, whereas the other has more iterations, so they are not the same.

Their relative strength will depend on the attacker's relative computation and memory bandwidth.
