### ISSUE TITLE
`Sha256Params::new`'s `round` parameter should probably not be a `usize`

### ISSUE THREAD

**Issue by tbu-** [RustCrypto/password-hashes#498]
[`Sha256Params::new`](https://docs.rs/sha-crypt/0.5.0/sha_crypt/struct.Sha256Params.html#method.new)

Since the number of rounds has nothing to do with the pointer width of the target CPU, a more concrete type like `u32` should probably be used. This is unfortunately a breaking change.

**Comment by tarcieri** [comment]
I agree a `u32` would probably be better. That's what we typically use for round counts in other crates. A breaking change is no problem: we're in the middle of a breaking change cycle.
