### ISSUE TITLE
The original bad password is mistyped

### ISSUE THREAD

**Issue by b100dian** [RustCrypto/password-hashes#514]
The hunter42 password used in the documentation  is a combination of the original [bad password](https://bash-org-archive.com/?244321) and the number 42.
I think the original hunter2 should be used unchanged.

**Comment by tarcieri** [comment]
If you really care, open a PR to change it. That said, I don't plan on working on that, and I don't think we need a tracking issue open to make sure the doc examples properly match a meme.
