### ISSUE TITLE
How to create password hash from string?

### ISSUE THREAD

**Issue by d47081** [RustCrypto/password-hashes#545]
Is any example how to create new `hash_string` for any algorithm presented in the [readme](https://github.com/RustCrypto/password-hashes?tab=readme-ov-file#usage)? Because I found dectyption and verification examples only.

Thanks

**Comment by tarcieri** [comment]
You're probably looking for:

https://github.com/RustCrypto/password-hashes/tree/master/password-auth

https://docs.rs/password-auth/latest/password_auth/fn.generate_hash.html

**Comment by tarcieri** [comment]
If you are interested in Argon2 specifically please read that crate’s docs: https://docs.rs/argon2/latest/argon2/#password-hashing
