### ISSUE TITLE
Secure usage of `scrypt` in WASM? Default parameters result in 30s runtime

### ISSUE THREAD

**Issue by thomaseizinger** [RustCrypto/password-hashes#66]
I am trying to use `scrypt` within a WASM environment and found that with the "recommended" parameters, using `scrypt_simple` takes about 33 seconds on my machine (t480, i7-8650U, 32GB RAM).

Any advice on how to deal with this situation?

**Comment by newpavlov** [comment]
Have you compiled your project using the `release` profile? Note that WASM can be up to 10 times slower than native code on such loads. It's not only WM overhead, but also lack of SIMD instructions.

**Comment by thomaseizinger** [comment]
Good idea compiling in release mode! 😅
Let me try :)

**Comment by thomaseizinger** [comment]
No issues at all in release mode :)
